#!/usr/bin/env bash

# Hook to check server against list of checks specified in CHECKS file.
#
# The CHECKS file may contain empty lines, comments (lines starting with #),
# settings (NAME=VALUE) and check instructions.
#
# The format of a check instruction is a path, optionally followed by the
# expected content.  For example:
#
#   /                       My Amazing App
#   /stylesheets/index.css  .body
#   /scripts/index.js       $(function()
#   /images/logo.png
#
# To check an application that supports multiple hostnames, use relative URLs
# that include the hostname, for example:
#
#  //admin.example.com     Admin Dashboard
#  //static.example.com/logo.png
#
# The default behavior is to wait for 5 seconds before running the first check,
# and timeout each check to 30 minutes.
#
# You can change these by setting WAIT and TIMEOUT to different values, for
# example:
#
#   WAIT=30     # Wait 1/2 minute
#   TIMEOUT=60  # Timeout after a minute
#

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
CONTAINERID="$1"; APP="$2"; PORT="$3" ; HOSTNAME="${4:-localhost}"

# Source in app env to get DOKKU_CHECKS_WAIT and any other necessary vars
[[ -f "$DOKKU_ROOT/$APP/ENV" ]] && source $DOKKU_ROOT/$APP/ENV

# Wait this many seconds (default 5) for server to start before running checks.
WAIT="${DOKKU_CHECKS_WAIT:-5}"
# Wait this many seconds (default 30) for each response.
TIMEOUT="${DOKKU_CHECKS_TIMEOUT:-30}"


# try to copy CHECKS from container if not in APP dir & quit gracefully if it doesn't exist
# docker cp exits with status 1 when run as non-root user when it tries to chown the file
# after successfully copying the file. Thus, we suppress stderr.
# ref: https://github.com/dotcloud/docker/issues/3986
TMPDIR=$(mktemp -d /tmp/CHECKS.XXXXX)
docker cp $CONTAINERID:/app/CHECKS $TMPDIR 2> /dev/null || true
if [[ ! -s "${TMPDIR}/CHECKS" ]] ; then
    echo "       CHECKS file not found in container. skipping checks."
    rm -rf $TMPDIR
    exit 0
else
    FILENAME=${TMPDIR}/CHECKS

    function cleanup() {
      rm -rf $TMPDIR
    }
    trap cleanup EXIT
fi


# Reads name/value pairs, sets the WAIT and TIMEOUT variables
exec < "$FILENAME"
while read LINE ; do
  # Name/value pair
  if [[ "$LINE" =~ ^.+= ]] ; then
    TRIM=${LINE%#*}
    NAME=${TRIM%=*}
    VALUE=${TRIM#*=}
    [[ "$NAME" = "WAIT" ]]    && WAIT=$VALUE
    [[ "$NAME" = "TIMEOUT" ]] && TIMEOUT=$VALUE
  fi
done


echo "-----> Waiting $WAIT seconds ..."
sleep $WAIT


# -q           do not use .curlrc (must come first)
# --compressed Test compression handled correctly
# --fail       Fail on server errors (4xx, 5xx)
# --location   Follow redirects
CURL_OPTIONS="-q --compressed --fail --location --max-time $TIMEOUT"


exec < "$FILENAME"
while read PATHNAME EXPECTED ; do
  # Ignore empty lines and lines starting with #
  [[ -z "$PATHNAME" || "$PATHNAME" =~ ^\# ]] && continue
  # Ignore variables
  [[ "$PATHNAME" =~ ^.+= ]] && continue


  if [[ "$PATHNAME" =~ ^//.+ ]] ; then
    # To test a URL with specific host name, we still make request to $HOSTNAME,
    # but we set Host header to $SEND_HOST.
    #
    # The pattern is
    #   //SEND_HOST/PATHNAME
    UNPREFIXED=${PATHNAME#//}
    SEND_HOST=${UNPREFIXED%%/*}
    PATHNAME=${UNPREFIXED#$SEND_HOST}

    # This URL will show up in the messages
    URL="http://$SEND_HOST$PATHNAME"
    # And how we formulate the CURL request
    CURL_ARGS="$CURL_OPTIONS http://$HOSTNAME:$PORT$PATHNAME -H Host:$SEND_HOST"
  else
    # This URL will show up in the messages
    URL="http://$HOSTNAME$PATHNAME"
    # And how we formulate the CURL request
    CURL_ARGS="$CURL_OPTIONS http://$HOSTNAME:$PORT$PATHNAME"
  fi

  function fail() {
    echo -e "       \033[31m\033[1m$URL: expected to but did not find: \"$EXPECTED\"\033[0m"
    exit 1
  }
  trap fail ERR

  echo -e "       \033[37m\033[1mcurl $CURL_ARGS\033[0m"
  HTML=$(curl $CURL_ARGS)
  [[ "$HTML" =~ "$EXPECTED" ]]
  echo -e "       \033[32m\033[1m$URL => \"$EXPECTED\"\033[0m"

  trap - ERR
done


echo -e "-----> \033[32m\033[1mAll checks successful!\033[0m"
